#!/usr/bin/env python3
"""Programmatic maintenance of a repository's `specs/GRIEVANCES.md` ledger.

The ledger is a committed markdown file that carries, per grievance, a
machine-owned JSON header and a human-owned prose body:

    <!-- grievance:GRV-0001 {"id": "GRV-0001", ...} -->
    <a id="grv-0001"></a>
    ### GRV-0001 - high - 2026-07-30 - short description

    `internal/worker/main.go:42` - declared in spec 156 review

    <!-- grievance:GRV-0001:prose -->

    **Finding.** ...
    <!-- /grievance:GRV-0001 -->

Those JSON headers are the single source of truth. The two index tables at the
top of the file (open grievances, then resolved ones) are DERIVED: every
mutation regenerates them and re-sorts both chronologically.

Ownership contract:
  - the tool owns the index tables, the `<!-- grievance:... -->` markers, the
    anchor, the `###` heading, the context line and the resolution log lines;
  - everything after `<!-- grievance:ID:prose -->` is yours, kept verbatim.

Usage:
    grievances.py init
    grievances.py add --short "..." --severity high [--locus f.go:42] [--finding ...]
    grievances.py resolve GRV-0001 --commit 1a2b3c4 [--note "..."]
    grievances.py resolve GRV-0002 --wont-fix --note "..."
    grievances.py resolve GRV-0003 --promoted-to specs/156-cdar-refresh/ --note "..."
    grievances.py reopen GRV-0001 --note "..."
    grievances.py bump GRV-0001
    grievances.py list [--status open|resolved|all] [--json]
    grievances.py show GRV-0001 [--json]
    grievances.py rebuild
    grievances.py check [--strict] [--all --root <pilot-root>]
    grievances.py migrate [--from specs/DOLEANCES.md]

Convention and lifecycle: the `grievances` skill (SKILL.md beside this script).
"""

from __future__ import annotations

import argparse
import datetime as dt
import json
import os
import re
import subprocess
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

LEDGER_BASENAME = "GRIEVANCES.md"
LEGACY_BASENAMES = ("DOLEANCES.md",)
SEVERITIES = ("critical", "high", "medium", "low")
RESOLUTION_KINDS = ("fixed", "wont-fix", "promoted")

OPEN_START = "<!-- grievances:index:open:start -->"
OPEN_END = "<!-- grievances:index:open:end -->"
RESOLVED_START = "<!-- grievances:index:resolved:start -->"
RESOLVED_END = "<!-- grievances:index:resolved:end -->"
# New detail blocks are inserted just before this marker, so a migrated file keeps
# its imported legacy prose below the indexed grievances.
DETAILS_END = "<!-- grievances:details:end -->"
GENERATED_NOTE = (
    "<!-- Generated by the `grievances` skill CLI. Do not edit these tables by hand: "
    "they are rebuilt from the JSON headers under `# Details` on every mutation. -->"
)

# Trailing blank lines are part of the match so that re-rendering normalizes the
# spacing between blocks instead of growing it on every mutation.
BLOCK_RE = re.compile(
    r"<!-- grievance:(GRV-\d{4}) (\{.*?\}) -->\n(.*?)<!-- /grievance:\1 -->\n*",
    re.DOTALL,
)
DATE_RE = re.compile(r"^\d{4}-\d{2}-\d{2}$")
COMMIT_RE = re.compile(r"^[0-9a-fA-F]{7,40}$")
ID_RE = re.compile(r"^GRV-\d{4}$")


class UserError(Exception):
    """A problem the caller can fix by changing the command line."""


# ── Model ──────────────────────────────────────────────────────────────────


@dataclass
class Grievance:
    id: str
    short: str
    severity: str
    date: str
    status: str = "open"
    occurrences: int = 1
    locus: str | None = None
    source: str | None = None
    tags: list[str] = field(default_factory=list)
    resolution: dict[str, Any] | None = None
    history: list[dict[str, Any]] = field(default_factory=list)

    @property
    def anchor(self) -> str:
        return self.id.lower()

    @classmethod
    def from_meta(cls, meta: dict[str, Any]) -> "Grievance":
        known = {f for f in cls.__dataclass_fields__}  # type: ignore[attr-defined]
        unknown = set(meta) - known
        if unknown:
            raise UserError(f"{meta.get('id', '?')}: unknown JSON field(s): {sorted(unknown)}")
        return cls(**meta)

    def to_meta(self) -> dict[str, Any]:
        meta: dict[str, Any] = {
            "id": self.id,
            "short": self.short,
            "severity": self.severity,
            "date": self.date,
            "status": self.status,
            "occurrences": self.occurrences,
        }
        if self.locus:
            meta["locus"] = self.locus
        if self.source:
            meta["source"] = self.source
        if self.tags:
            meta["tags"] = self.tags
        if self.resolution:
            meta["resolution"] = self.resolution
        if self.history:
            meta["history"] = self.history
        return meta

    # ── Rendering (tool-owned lines) ───────────────────────────────────────

    def heading(self) -> str:
        seen = f" · ×{self.occurrences}" if self.occurrences > 1 else ""
        return f"### {self.id} · {self.severity} · {self.date}{seen} — {self.short}"

    def context_line(self) -> str | None:
        parts: list[str] = []
        if self.locus:
            parts.append(f"`{self.locus}`")
        if self.source:
            parts.append(f"declared in {self.source}")
        if self.tags:
            parts.append("tags: " + ", ".join(f"`{t}`" for t in self.tags))
        return " · ".join(parts) if parts else None

    @staticmethod
    def render_log_entry(entry: dict[str, Any]) -> str:
        action = entry.get("action")
        date = entry.get("date", "?")
        note = (entry.get("note") or "").strip()
        if action == "reopened":
            line = f"**Reopened {date}**"
            return f"{line} — {note}" if note else line
        kind = entry.get("kind", "fixed")
        if kind == "fixed":
            line = f"**Resolved {date}**"
            if note:
                line += f" — {note}"
            commit = entry.get("commit")
            if commit:
                line += f" · `{commit}`"
            return line
        if kind == "wont-fix":
            line = f"**Closed {date} — won't fix**"
            return f"{line} — {note}" if note else line
        line = f"**Closed {date} — promoted**"
        if note:
            line += f" — {note}"
        ref = entry.get("ref")
        if ref:
            line += f" → `{ref}`"
        return line

    def resolution_cells(self) -> tuple[str, str]:
        """(resolved date, commit-or-ref) cells for the resolved index table."""
        res = self.resolution or {}
        date = res.get("date", "")
        kind = res.get("kind", "fixed")
        if kind == "fixed":
            commit = res.get("commit", "")
            return date, f"`{commit}`" if commit else ""
        if kind == "wont-fix":
            return date, "won't fix"
        ref = res.get("ref", "")
        return date, f"promoted → `{ref}`" if ref else "promoted"


# ── File parsing / rendering ───────────────────────────────────────────────


@dataclass
class Ledger:
    path: Path
    text: str
    grievances: list[Grievance]
    prose: dict[str, str]

    @classmethod
    def load(cls, path: Path) -> "Ledger":
        if not path.is_file():
            raise UserError(
                f"no ledger at {path}\n"
                f"create it with: {Path(sys.argv[0]).name} init --file {path}"
            )
        text = path.read_text(encoding="utf-8")
        for marker in (OPEN_START, OPEN_END, RESOLVED_START, RESOLVED_END):
            if marker not in text:
                raise UserError(
                    f"{path}: missing index marker {marker}\n"
                    "this file predates the programmatic format — run: "
                    f"{Path(sys.argv[0]).name} migrate --from {path}"
                )
        grievances: list[Grievance] = []
        prose: dict[str, str] = {}
        seen: set[str] = set()
        for match in BLOCK_RE.finditer(text):
            gid, raw_meta, body = match.group(1), match.group(2), match.group(3)
            try:
                meta = json.loads(raw_meta)
            except json.JSONDecodeError as exc:
                raise UserError(f"{path}: {gid} has an unparseable JSON header: {exc}") from exc
            if meta.get("id") != gid:
                raise UserError(f"{path}: {gid} marker disagrees with its JSON id {meta.get('id')!r}")
            if gid in seen:
                raise UserError(f"{path}: {gid} appears twice")
            seen.add(gid)
            grievances.append(Grievance.from_meta(meta))
            prose[gid] = extract_prose(gid, body)
        return cls(path=path, text=text, grievances=grievances, prose=prose)

    def get(self, gid: str) -> Grievance:
        for g in self.grievances:
            if g.id == gid:
                return g
        raise UserError(f"{self.path}: no such grievance: {gid}")

    def next_id(self) -> str:
        numbers = [int(g.id.split("-")[1]) for g in self.grievances]
        return f"GRV-{max(numbers, default=0) + 1:04d}"

    def append(self, g: Grievance, prose: str) -> None:
        self.grievances.append(g)
        self.prose[g.id] = prose
        block = render_block(g, prose)
        matches = list(BLOCK_RE.finditer(self.text))
        if DETAILS_END in self.text:
            insert_at = self.text.index(DETAILS_END)
            self.text = self.text[:insert_at] + block + "\n" + self.text[insert_at:]
        elif matches:
            insert_at = matches[-1].end()
            self.text = self.text[:insert_at] + block + "\n" + self.text[insert_at:]
        else:
            self.text = self.text.rstrip("\n") + "\n\n" + block

    def render(self) -> str:
        text = self.text
        # Rewrite every detail block from its (possibly mutated) model.
        def replace(match: re.Match[str]) -> str:
            gid = match.group(1)
            return render_block(self.get(gid), self.prose[gid]) + "\n"

        text = BLOCK_RE.sub(replace, text)
        text = replace_region(text, OPEN_START, OPEN_END, self.render_open_index())
        text = replace_region(text, RESOLVED_START, RESOLVED_END, self.render_resolved_index())
        return text.rstrip("\n") + "\n"

    def render_open_index(self) -> str:
        rows = sorted(
            (g for g in self.grievances if g.status == "open"),
            key=lambda g: (g.date, g.id),
        )
        lines = [GENERATED_NOTE, "", f"## Open grievances ({len(rows)})", ""]
        if not rows:
            lines.append("_None._")
            return "\n".join(lines)
        lines += [
            "| ID | Date | Severity | Seen | Short description |",
            "|---|---|---|---|---|",
        ]
        for g in rows:
            lines.append(
                f"| [{g.id}](#{g.anchor}) | {g.date} | {g.severity} | ×{g.occurrences} "
                f"| {cell(g.short)} |"
            )
        return "\n".join(lines)

    def render_resolved_index(self) -> str:
        rows = sorted(
            (g for g in self.grievances if g.status == "resolved"),
            key=lambda g: ((g.resolution or {}).get("date", ""), g.id),
        )
        lines = [f"## Resolved grievances ({len(rows)})", ""]
        if not rows:
            lines.append("_None._")
            return "\n".join(lines)
        lines += [
            "| ID | Date | Severity | Seen | Short description | Resolved | Commit |",
            "|---|---|---|---|---|---|---|",
        ]
        for g in rows:
            resolved_date, ref = g.resolution_cells()
            lines.append(
                f"| [{g.id}](#{g.anchor}) | {g.date} | {g.severity} | ×{g.occurrences} "
                f"| {cell(g.short)} | {resolved_date} | {cell(ref)} |"
            )
        return "\n".join(lines)


def extract_prose(gid: str, body: str) -> str:
    """Return the human-owned part of a detail block."""
    marker = f"<!-- grievance:{gid}:prose -->"
    if marker in body:
        return body.split(marker, 1)[1].strip("\n")
    # Hand-written or pre-marker block: everything after the `###` heading.
    lines = body.split("\n")
    for i, line in enumerate(lines):
        if line.startswith("### "):
            return "\n".join(lines[i + 1 :]).strip("\n")
    return body.strip("\n")


def render_block(g: Grievance, prose: str) -> str:
    meta = json.dumps(g.to_meta(), ensure_ascii=False, sort_keys=True)
    lines = [
        f"<!-- grievance:{g.id} {meta} -->",
        f'<a id="{g.anchor}"></a>',
        g.heading(),
    ]
    context = g.context_line()
    if context:
        lines += ["", context]
    for entry in g.history:
        lines += ["", Grievance.render_log_entry(entry)]
    lines += ["", f"<!-- grievance:{g.id}:prose -->"]
    prose = prose.strip("\n")
    if prose:
        lines += ["", prose]
    lines += ["", f"<!-- /grievance:{g.id} -->"]
    return "\n".join(lines) + "\n"


def replace_region(text: str, start: str, end: str, body: str) -> str:
    head, _, rest = text.partition(start)
    _, _, tail = rest.partition(end)
    return f"{head}{start}\n{body}\n{end}{tail}"


def cell(value: str) -> str:
    return value.replace("|", r"\|").replace("\n", " ").strip()


# ── Validation helpers ─────────────────────────────────────────────────────


def today() -> str:
    return dt.date.today().isoformat()


def check_date(value: str | None) -> str:
    if value in (None, "", "today"):
        return today()
    assert value is not None
    if not DATE_RE.match(value):
        raise UserError(f"invalid date {value!r}: expected YYYY-MM-DD (or 'today')")
    try:
        dt.date.fromisoformat(value)
    except ValueError as exc:
        raise UserError(f"invalid date {value!r}: {exc}") from exc
    return value


def check_short(value: str) -> str:
    short = " ".join(value.split())
    if not short:
        raise UserError("--short must not be empty")
    if len(short) > 120:
        raise UserError(f"--short is {len(short)} chars; keep it under 120 (the long story goes in --finding)")
    return short


def check_id(value: str) -> str:
    if not ID_RE.match(value):
        raise UserError(f"invalid grievance id {value!r}: expected GRV-NNNN")
    return value


# ── Templates ──────────────────────────────────────────────────────────────


def ledger_template() -> str:
    return f"""# Grievances — ledger of non-blocking findings

> Committed register of underlying problems, technical debt and improvements met
> **outside the scope of an in-flight spec**: "what works, but will not scale, or
> only holds together with tape". Committed on purpose — friction should
> accumulate visibly.
>
> **This file is maintained programmatically.** Declare and close entries with the
> `grievances` skill CLI; never hand-edit the index tables below:
>
> ```bash
> grievances.py add --short "..." --severity high --locus "file.go:42" \\
>   --finding "..." --impact "..." --fix "..." --effort 0.5d
> grievances.py resolve GRV-0001 --commit 1a2b3c4 --note "..."
> ```
>
> Prose under `# Details` is human-owned and kept verbatim; the heading lines, the
> `<!-- grievance:... -->` markers and both tables belong to the tool, which
> re-sorts them chronologically on every mutation.
>
> **Boundary.** Anything regulatory, security-related, data-losing or needing an
> arbitration does NOT stay here: it becomes a spec, or a fiche in the pilot
> `ROADMAP.md`, immediately — close the grievance with `--promoted-to <ref>` so a
> one-line pointer remains and the analysis lives in exactly one artifact.
>
> Never paste a secret, a token or a credential-bearing log line into an entry:
> record the *command* that retrieves a credential, never its value.
>
> When to read and when to write: `specs/CLAUDE.md`.

{OPEN_START}
{GENERATED_NOTE}

## Open grievances (0)

_None._
{OPEN_END}

{RESOLVED_START}
## Resolved grievances (0)

_None._
{RESOLVED_END}

---

# Details

<!-- One block per grievance, appended by the CLI. Newest last. Prose inside a
     block is yours; the heading and the markers around it are the tool's. -->

{DETAILS_END}
"""


def specs_claude_template() -> str:
    return """# specs/ — scope guidance

> Refines the root `CLAUDE.md`.

## GRIEVANCES.md — when to read it, when to write to it

`specs/GRIEVANCES.md` is the register of **underlying problems, technical debt and
improvements found outside the scope of an in-flight spec**: "what works, but will
not scale, or only holds together with tape". It lives here because a grievance is
the raw material a spec is made of — one step upstream, in the same folder.

It is **not** `ROADMAP.md` (upcoming features) and not the pilot `ROADMAP.md`
(cross-repo fiches).

### Read it

- **Before starting on an unfamiliar area** — the fastest briefing on what will
  waste your time here. The open-grievance table at the top of the file is the
  whole summary; click an ID for the analysis.
- **When opening a new spec** — grep it for the area you are about to touch: a
  finding already analysed in that zone often belongs *inside* your spec's scope,
  and closing it while you are already there costs a fraction of a dedicated pass.

### Write to it — with the CLI, never by hand

Declare a finding the moment you meet it:

```bash
grievances.py add --short "worker co-hosted with the API will not scale" \\
  --severity high --locus "internal/worker/main.go:42" \\
  --source "spec 156 implementation" \\
  --finding "..." --impact "..." --fix "..." --effort 1d
```

Close it when a commit fixes it:

```bash
grievances.py resolve GRV-0007 --commit 1a2b3c4 --note "worker runs in its own deployment"
```

Met the same friction again? `grievances.py bump GRV-0007` — frequency is the
severity signal, and a duplicate entry hides it.

At the **end of every implementation / test / review phase**, say in one sentence
what you changed, **including "no change"**: a silent no-op is indistinguishable
from forgetting, and that is what kills ledgers.

### The boundary — what does NOT belong here

| Not this | Where it goes |
|---|---|
| A defect with a regulatory, security, data-loss or money dimension | A spec here, or a fiche in the **pilot** `ROADMAP.md` — immediately |
| Anything needing an arbitration or a design decision | A pilot roadmap fiche with a named arbiter |
| A task on the spec in flight | That spec's `tasks.md` |
| A finding on the diff under review | That spec's `review.md` |
| A live incident | The incident/debug report, then a pilot roadmap fiche |
| "This module should be rewritten" | Nowhere — that is an opinion. Make it a proposal with evidence, or drop it |

**One fact lives in exactly one artifact.** A promoted finding leaves this file:
`grievances.py resolve GRV-000N --promoted-to <spec-or-fiche>` keeps the pointer,
never a restatement.

Never paste a secret, a token, or a credential-bearing log line into an entry.

Format contract, lifecycle and the full CLI: the `grievances` skill.
"""


ROOT_CLAUDE_POINTER = """**`specs/GRIEVANCES.md` is the ledger of non-blocking findings** — underlying
problems, technical debt and improvements met outside the scope of an in-flight
spec. Read the open-grievance table at the top before starting on an unfamiliar
area, and **update the ledger at the end of every implementation / test / review
phase** — always through the CLI, never by hand:
`grievances.py add --short "..." --severity high --locus "file:line" --finding "..." --impact "..." --fix "..."`,
`grievances.py resolve GRV-000N --commit <hash>`, `grievances.py bump GRV-000N`.
Anything regulatory, security-related, data-losing or needing an arbitration is
**promoted** out to a spec or a pilot-ROADMAP fiche
(`resolve --promoted-to <ref>`), leaving a one-line pointer. Then say in one
sentence what you changed — including "no change". When to read, when to write,
and the full boundary: `specs/CLAUDE.md`.
"""


# ── Path resolution ────────────────────────────────────────────────────────


def git_root(start: Path) -> Path | None:
    try:
        out = subprocess.run(
            ["git", "-C", str(start), "rev-parse", "--show-toplevel"],
            check=True,
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.DEVNULL,
        )
    except (OSError, subprocess.CalledProcessError):
        return None
    return Path(out.stdout.strip())


def resolve_ledger_path(args: argparse.Namespace) -> Path:
    if getattr(args, "file", None):
        return Path(args.file).expanduser().resolve()
    env = os.environ.get("GRIEVANCES_FILE")
    if env:
        return Path(env).expanduser().resolve()
    repo = Path(getattr(args, "repo", None) or ".").expanduser().resolve()
    root = git_root(repo) or repo
    return root / "specs" / LEDGER_BASENAME


def write_text(path: Path, text: str, dry_run: bool) -> None:
    if dry_run:
        sys.stdout.write(text)
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(text, encoding="utf-8")
    tmp.replace(path)


def save(ledger: Ledger, dry_run: bool) -> None:
    write_text(ledger.path, ledger.render(), dry_run)


def emit(payload: dict[str, Any], as_json: bool, human: str) -> None:
    if as_json:
        print(json.dumps(payload, ensure_ascii=False, sort_keys=True))
    else:
        print(human)


# ── Commands ───────────────────────────────────────────────────────────────


def cmd_init(args: argparse.Namespace) -> int:
    path = resolve_ledger_path(args)
    created: list[str] = []
    if path.exists():
        print(f"= {path} already exists — untouched")
    else:
        write_text(path, ledger_template(), args.dry_run)
        created.append(str(path))
        print(f"+ {path}")
    guidance = path.parent / "CLAUDE.md"
    if guidance.exists():
        if LEDGER_BASENAME not in guidance.read_text(encoding="utf-8"):
            print(f"! {guidance} exists but never mentions {LEDGER_BASENAME} — add the guidance by hand")
    else:
        write_text(guidance, specs_claude_template(), args.dry_run)
        created.append(str(guidance))
        print(f"+ {guidance}")
    root_claude = path.parent.parent / "CLAUDE.md"
    if not root_claude.exists():
        print(f"! no {root_claude} — nothing to point at the ledger from")
    elif f"specs/{LEDGER_BASENAME}" not in root_claude.read_text(encoding="utf-8"):
        print(f"! {root_claude} does not point at specs/{LEDGER_BASENAME}; paste this block into it:\n")
        print(ROOT_CLAUDE_POINTER)
    if created and not args.dry_run:
        print("commit: docs(grievances): add the non-blocking findings ledger and its scope guidance")
    return 0


def build_prose(args: argparse.Namespace) -> str:
    if getattr(args, "body_file", None):
        return Path(args.body_file).expanduser().read_text(encoding="utf-8").strip("\n")
    parts: list[str] = []
    if args.finding:
        parts.append(f"**Finding.** {args.finding.strip()}")
    if args.impact:
        parts.append(f"**Impact.** {args.impact.strip()}")
    if args.why_tests_miss:
        parts.append(f"**Why the tests miss it.** {args.why_tests_miss.strip()}")
    fix = (args.fix or "").strip()
    if fix or args.effort:
        line = f"**Fix.** {fix}" if fix else "**Fix.** _to be decided._"
        if args.effort:
            line += f" **Effort: {args.effort.strip()}.**"
        parts.append(line)
    return "\n\n".join(parts)


def cmd_add(args: argparse.Namespace) -> int:
    path = resolve_ledger_path(args)
    ledger = Ledger.load(path)
    short = check_short(args.short)
    date = check_date(args.date)
    if args.severity not in SEVERITIES:
        raise UserError(f"--severity must be one of {', '.join(SEVERITIES)}")
    if not args.force:
        needle = short.lower()
        for g in ledger.grievances:
            if g.status == "open" and g.short.lower() == needle:
                raise UserError(
                    f"{g.id} already carries this exact short description.\n"
                    f"met it again? bump the counter instead: grievances.py bump {g.id}\n"
                    "genuinely a distinct finding? re-run with --force"
                )
    if not args.impact and not args.body_file and not args.allow_no_impact:
        raise UserError(
            "--impact is required: an entry without an impact line gets ignored forever.\n"
            "pass --allow-no-impact only for a pure papercut whose cost is self-evident"
        )
    grievance = Grievance(
        id=ledger.next_id(),
        short=short,
        severity=args.severity,
        date=date,
        locus=args.locus,
        source=args.source,
        tags=list(args.tag or []),
    )
    ledger.append(grievance, build_prose(args))
    save(ledger, args.dry_run)
    emit(
        {"id": grievance.id, "file": str(path), "status": "open", "anchor": f"#{grievance.anchor}"},
        args.json,
        f"{grievance.id} declared ({grievance.severity}, {grievance.date}) in {path}",
    )
    return 0


def cmd_resolve(args: argparse.Namespace) -> int:
    path = resolve_ledger_path(args)
    ledger = Ledger.load(path)
    grievance = ledger.get(check_id(args.id))
    if grievance.status == "resolved" and not args.force:
        res = grievance.resolution or {}
        raise UserError(
            f"{grievance.id} is already resolved ({res.get('date')}, {res.get('kind')}). "
            "use --force to overwrite, or reopen it first"
        )
    date = check_date(args.date)
    selected = [flag for flag in (args.commit, args.wont_fix, args.promoted_to) if flag]
    if len(selected) != 1:
        raise UserError("pass exactly one of --commit <hash>, --wont-fix, --promoted-to <ref>")
    entry: dict[str, Any] = {"action": "resolved", "date": date}
    if args.commit:
        if not COMMIT_RE.match(args.commit):
            raise UserError(f"invalid commit hash {args.commit!r}: expected 7-40 hex characters")
        entry.update(kind="fixed", commit=args.commit.lower())
    elif args.wont_fix:
        if not args.note:
            raise UserError("--wont-fix requires --note: say why, in the file, once and for all")
        entry.update(kind="wont-fix")
    else:
        entry.update(kind="promoted", ref=args.promoted_to)
    if args.note:
        entry["note"] = args.note.strip()
    grievance.status = "resolved"
    grievance.resolution = {k: v for k, v in entry.items() if k != "action"}
    grievance.history.append(entry)
    save(ledger, args.dry_run)
    emit(
        {"id": grievance.id, "file": str(path), "status": "resolved", "resolution": grievance.resolution},
        args.json,
        f"{grievance.id} resolved ({entry['kind']}, {date}) in {path}",
    )
    return 0


def cmd_reopen(args: argparse.Namespace) -> int:
    path = resolve_ledger_path(args)
    ledger = Ledger.load(path)
    grievance = ledger.get(check_id(args.id))
    if grievance.status != "resolved":
        raise UserError(f"{grievance.id} is already open")
    date = check_date(args.date)
    entry: dict[str, Any] = {"action": "reopened", "date": date}
    if args.note:
        entry["note"] = args.note.strip()
    grievance.status = "open"
    grievance.resolution = None
    grievance.history.append(entry)
    save(ledger, args.dry_run)
    emit(
        {"id": grievance.id, "file": str(path), "status": "open"},
        args.json,
        f"{grievance.id} reopened ({date}) in {path}",
    )
    return 0


def cmd_bump(args: argparse.Namespace) -> int:
    path = resolve_ledger_path(args)
    ledger = Ledger.load(path)
    grievance = ledger.get(check_id(args.id))
    if grievance.status != "open":
        raise UserError(f"{grievance.id} is resolved — reopen it before counting a new occurrence")
    grievance.occurrences += 1
    if args.date or args.redate:
        grievance.date = check_date(args.date)
    save(ledger, args.dry_run)
    emit(
        {"id": grievance.id, "file": str(path), "occurrences": grievance.occurrences},
        args.json,
        f"{grievance.id} seen ×{grievance.occurrences}",
    )
    return 0


def cmd_list(args: argparse.Namespace) -> int:
    path = resolve_ledger_path(args)
    ledger = Ledger.load(path)
    rows = [g for g in ledger.grievances if args.status in ("all", g.status)]
    if args.severity:
        rows = [g for g in rows if g.severity in args.severity]
    rows.sort(key=lambda g: (g.date, g.id))
    if args.json:
        print(json.dumps([g.to_meta() for g in rows], ensure_ascii=False, sort_keys=True))
        return 0
    if not rows:
        print("no grievance matches")
        return 0
    for g in rows:
        seen = f" ×{g.occurrences}" if g.occurrences > 1 else ""
        suffix = ""
        if g.status == "resolved":
            resolved_date, ref = g.resolution_cells()
            suffix = f"  [resolved {resolved_date} {ref}]"
        print(f"{g.id}  {g.date}  {g.severity:<8}{seen:<4} {g.short}{suffix}")
    return 0


def cmd_show(args: argparse.Namespace) -> int:
    path = resolve_ledger_path(args)
    ledger = Ledger.load(path)
    grievance = ledger.get(check_id(args.id))
    if args.json:
        payload = grievance.to_meta()
        payload["prose"] = ledger.prose[grievance.id]
        print(json.dumps(payload, ensure_ascii=False, sort_keys=True))
        return 0
    sys.stdout.write(render_block(grievance, ledger.prose[grievance.id]))
    return 0


def cmd_rebuild(args: argparse.Namespace) -> int:
    path = resolve_ledger_path(args)
    ledger = Ledger.load(path)
    rendered = ledger.render()
    changed = rendered != ledger.text
    if args.dry_run:
        sys.stdout.write(rendered)
    elif changed:
        write_text(path, rendered, dry_run=False)
    print(f"{path}: {'rewritten' if changed else 'already normalized'}")
    return 0


def audit_repo(repo: Path, strict: bool) -> tuple[int, list[str]]:
    """Return (problem count, report lines) for one repository."""
    lines: list[str] = []
    problems = 0
    specs = repo / "specs"
    if not specs.is_dir():
        return 0, ["  ! no specs/ directory — nowhere canonical to host the ledger"]
    ledger_path = specs / LEDGER_BASENAME
    for legacy in LEGACY_BASENAMES:
        for stray in (repo / legacy, specs / legacy):
            if stray.is_file():
                problems += 1
                rel = stray.relative_to(repo)
                lines.append(f"  x legacy ledger present: {rel} — canonical name is specs/{LEDGER_BASENAME}")
                lines.append(f"    migrate it: grievances.py migrate --from {stray}")
    if (repo / LEDGER_BASENAME).is_file():
        problems += 1
        lines.append(f"  x misplaced at the repo root: {LEDGER_BASENAME} — move it to specs/")
    if not ledger_path.is_file():
        problems += 1
        lines.append(f"  x specs/{LEDGER_BASENAME} is MISSING — create it: grievances.py init --repo {repo}")
    else:
        try:
            ledger = Ledger.load(ledger_path)
        except UserError as exc:
            problems += 1
            lines.append(f"  x specs/{LEDGER_BASENAME}: {exc}")
        else:
            open_count = sum(1 for g in ledger.grievances if g.status == "open")
            resolved = len(ledger.grievances) - open_count
            lines.append(
                f"  v specs/{LEDGER_BASENAME} — {open_count} open, {resolved} resolved"
            )
            for g in ledger.grievances:
                if g.severity not in SEVERITIES:
                    problems += 1
                    lines.append(f"  x {g.id}: unknown severity {g.severity!r}")
                if not DATE_RE.match(g.date):
                    problems += 1
                    lines.append(f"  x {g.id}: date {g.date!r} is not YYYY-MM-DD")
                if g.status not in ("open", "resolved"):
                    problems += 1
                    lines.append(f"  x {g.id}: unknown status {g.status!r}")
                if g.status == "resolved":
                    res = g.resolution or {}
                    if res.get("kind") not in RESOLUTION_KINDS:
                        problems += 1
                        lines.append(f"  x {g.id}: resolved without a valid resolution kind")
                    elif res["kind"] == "fixed" and not COMMIT_RE.match(res.get("commit", "")):
                        problems += 1
                        lines.append(f"  x {g.id}: resolved as fixed without a commit hash")
                    if not DATE_RE.match(res.get("date", "")):
                        problems += 1
                        lines.append(f"  x {g.id}: resolved without a valid date")
                last = g.history[-1] if g.history else None
                expected = "resolved" if g.status == "resolved" else None
                if last and expected and last.get("action") != expected:
                    problems += 1
                    lines.append(f"  x {g.id}: status {g.status!r} contradicts its history")
            if strict and ledger.render() != ledger.text:
                problems += 1
                lines.append("  x file is not normalized (tables or headings drifted) — run: grievances.py rebuild")
    guidance = specs / "CLAUDE.md"
    if not guidance.is_file():
        problems += 1
        lines.append("  x specs/CLAUDE.md is MISSING (the when-to-read / when-to-write guidance)")
    elif LEDGER_BASENAME not in guidance.read_text(encoding="utf-8"):
        problems += 1
        lines.append(f"  x specs/CLAUDE.md never mentions {LEDGER_BASENAME}")
    root_claude = repo / "CLAUDE.md"
    if not root_claude.is_file():
        lines.append("  ! no root CLAUDE.md — nothing to point from")
    elif f"specs/{LEDGER_BASENAME}" not in root_claude.read_text(encoding="utf-8"):
        problems += 1
        lines.append(f"  x root CLAUDE.md does not point at specs/{LEDGER_BASENAME}")
    return problems, lines


def cmd_check(args: argparse.Namespace) -> int:
    if args.all:
        root = Path(args.root or ".").expanduser().resolve()
        repos = sorted(p.parent for p in root.glob("*/.git"))
        if not repos:
            print(f"no git repository found under {root}", file=sys.stderr)
            return 2
    else:
        target = resolve_ledger_path(args)
        repos = [target.parent.parent]
    total = 0
    compliant = 0
    for repo in repos:
        problems, lines = audit_repo(repo, args.strict)
        print(repo.name if args.all else str(repo))
        for line in lines:
            print(line)
        print()
        total += problems
        compliant += 1 if problems == 0 else 0
    print(f"{compliant}/{len(repos)} repo(s) compliant" + (f" · {total} problem(s)" if total else ""))
    return 0 if total == 0 else 1


def cmd_migrate(args: argparse.Namespace) -> int:
    target = resolve_ledger_path(args)
    if args.source:
        source = Path(args.source).expanduser().resolve()
    else:
        source = target.parent / LEGACY_BASENAMES[0]
    if not source.is_file():
        raise UserError(f"no legacy ledger at {source}")
    if source == target:
        raise UserError("source and target are the same file")
    if target.exists():
        raise UserError(f"{target} already exists — merge by hand, this command never overwrites")
    legacy = source.read_text(encoding="utf-8")
    body_lines = legacy.split("\n")
    if body_lines and body_lines[0].startswith("# "):
        body_lines = body_lines[1:]
    legacy_body = "\n".join(body_lines).strip("\n")
    migrated = (
        ledger_template().rstrip("\n")
        + "\n\n---\n\n"
        + f"## Legacy ledger — imported verbatim from `{source.name}` on {today()}\n\n"
        + "> Not indexed: these sessions predate the programmatic format and are kept\n"
        + "> as written. Anything still open here should be re-declared with\n"
        + "> `grievances.py add` so it appears in the table at the top, then struck\n"
        + "> from this section.\n\n"
        + legacy_body
        + "\n"
    )
    write_text(target, migrated, args.dry_run)
    if args.dry_run:
        return 0
    print(f"+ {target} (legacy content preserved under '## Legacy ledger')")
    if args.keep_legacy:
        print(f"= {source} kept (--keep-legacy)")
    else:
        removed = False
        if git_root(source.parent):
            removed = (
                subprocess.run(
                    ["git", "-C", str(source.parent), "rm", "--quiet", "--", source.name],
                    stdout=subprocess.DEVNULL,
                    stderr=subprocess.DEVNULL,
                ).returncode
                == 0
            )
        if not removed:
            source.unlink()
        print(f"- {source}")
    guidance = target.parent / "CLAUDE.md"
    if guidance.is_file():
        print(f"! {guidance} still describes the old file — update its ledger section by hand")
    print(f"! update the repo root CLAUDE.md pointer to specs/{LEDGER_BASENAME}")
    print("commit: docs(grievances)!: rename the ledger to GRIEVANCES.md and index it programmatically")
    return 0


# ── CLI ────────────────────────────────────────────────────────────────────


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="grievances.py",
        description="Declare, close and audit non-blocking findings in specs/GRIEVANCES.md.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    sub = parser.add_subparsers(dest="command", required=True)

    def with_common(p: argparse.ArgumentParser, *, json_flag: bool = True) -> argparse.ArgumentParser:
        p.add_argument("--file", help=f"ledger path (default: <git root>/specs/{LEDGER_BASENAME})")
        p.add_argument("--repo", help="repository root to resolve the default ledger path from")
        p.add_argument("--dry-run", action="store_true", help="print the resulting file, write nothing")
        if json_flag:
            p.add_argument("--json", action="store_true", help="machine-readable output")
        return p

    p_init = with_common(sub.add_parser("init", help="create the ledger and its specs/CLAUDE.md guidance"), json_flag=False)
    p_init.set_defaults(func=cmd_init)

    p_add = with_common(sub.add_parser("add", help="declare a grievance"))
    p_add.add_argument("--short", required=True, help="one-line description, under 120 chars (table column)")
    p_add.add_argument("--severity", required=True, choices=SEVERITIES)
    p_add.add_argument("--date", help="declaration date, YYYY-MM-DD (default: today)")
    p_add.add_argument("--locus", help="where it is observed, e.g. internal/worker/main.go:42")
    p_add.add_argument("--source", help="what surfaced it, e.g. 'spec 156 review'")
    p_add.add_argument("--tag", action="append", help="repeatable free-form tag")
    p_add.add_argument("--finding", help="what is observed")
    p_add.add_argument("--impact", help="what doing nothing costs (required)")
    p_add.add_argument("--why-tests-miss", help="why the suite does not catch it")
    p_add.add_argument("--fix", help="the direction of the fix")
    p_add.add_argument("--effort", help="indicative effort, e.g. 0.5d")
    p_add.add_argument("--body-file", help="read the whole prose body from this markdown file instead")
    p_add.add_argument("--allow-no-impact", action="store_true", help="papercut whose cost is self-evident")
    p_add.add_argument("--force", action="store_true", help="declare even if an open grievance has the same --short")
    p_add.set_defaults(func=cmd_add)

    p_res = with_common(sub.add_parser("resolve", help="close a grievance: date + commit hash"))
    p_res.add_argument("id")
    p_res.add_argument("--commit", help="commit hash that closed it (7-40 hex chars)")
    p_res.add_argument("--wont-fix", action="store_true", help="close without a fix; requires --note")
    p_res.add_argument("--promoted-to", help="close because it became a spec or a roadmap fiche")
    p_res.add_argument("--date", help="resolution date, YYYY-MM-DD (default: today)")
    p_res.add_argument("--note", help="one line on what closed it")
    p_res.add_argument("--force", action="store_true", help="overwrite an existing resolution")
    p_res.set_defaults(func=cmd_resolve)

    p_reo = with_common(sub.add_parser("reopen", help="move a resolved grievance back to the open table"))
    p_reo.add_argument("id")
    p_reo.add_argument("--date", help="reopening date, YYYY-MM-DD (default: today)")
    p_reo.add_argument("--note", help="why it is back")
    p_reo.set_defaults(func=cmd_reopen)

    p_bump = with_common(sub.add_parser("bump", help="count another occurrence instead of duplicating an entry"))
    p_bump.add_argument("id")
    p_bump.add_argument("--date", help="also move the entry's date to this one")
    p_bump.add_argument("--redate", action="store_true", help="also move the entry's date to today")
    p_bump.set_defaults(func=cmd_bump)

    p_list = with_common(sub.add_parser("list", help="list grievances"))
    p_list.add_argument("--status", choices=("open", "resolved", "all"), default="open")
    p_list.add_argument("--severity", action="append", choices=SEVERITIES)
    p_list.set_defaults(func=cmd_list)

    p_show = with_common(sub.add_parser("show", help="print one grievance"))
    p_show.add_argument("id")
    p_show.set_defaults(func=cmd_show)

    p_reb = with_common(sub.add_parser("rebuild", help="regenerate the tables and headings, re-sorted"), json_flag=False)
    p_reb.set_defaults(func=cmd_rebuild)

    p_chk = with_common(sub.add_parser("check", help="audit the ledger, its guidance and its pointers"), json_flag=False)
    p_chk.add_argument("--strict", action="store_true", help="also fail when the file is not normalized")
    p_chk.add_argument("--all", action="store_true", help="audit every git repo directly under --root")
    p_chk.add_argument("--root", help="pilot root holding the repos to audit (with --all)")
    p_chk.set_defaults(func=cmd_check)

    p_mig = with_common(sub.add_parser("migrate", help="rename a legacy DOLEANCES.md and index it"), json_flag=False)
    p_mig.add_argument("--from", dest="source", help=f"legacy ledger (default: <specs>/{LEGACY_BASENAMES[0]})")
    p_mig.add_argument("--keep-legacy", action="store_true", help="do not delete the legacy file")
    p_mig.set_defaults(func=cmd_migrate)

    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    try:
        return int(args.func(args))
    except UserError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    sys.exit(main())
